# Generated by Django 3.2.16 on 2023-08-22 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('education', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh')], max_length=20)),
                ('caste', models.CharField(choices=[('brahmin', 'Brahmin'), ('kshatriya', 'Kshatriya'), ('vaishya', 'Vaishya'), ('shudra', 'Shudra'), ('darzi', 'Darzi'), ('jolaha', 'Jolaha'), ('fakir', 'Fakir'), ('rangrez', 'Rangrez')], max_length=20)),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode (Calicut)'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=50)),
                ('place', models.CharField(choices=[('Thiruvananthapuram', [('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kovalam', 'Kovalam'), ('Neyyattinkara', 'Neyyattinkara'), ('Attingal', 'Attingal'), ('Varkala', 'Varkala')]), ('Kollam', [('Kollam', 'Kollam'), ('Paravur', 'Paravur'), ('Punalur', 'Punalur'), ('Karunagappally', 'Karunagappally')]), ('Pathanamthitta', [('Pathanamthitta', 'Pathanamthitta'), ('Adoor', 'Adoor'), ('Thiruvalla', 'Thiruvalla'), ('Ranni', 'Ranni')]), ('Alappuzha', [('Alappuzha', 'Alappuzha'), ('Chengannur', 'Chengannur'), ('Kayamkulam', 'Kayamkulam'), ('Haripad', 'Haripad'), ('Ambalappuzha', 'Ambalappuzha')]), ('Kottayam', [('Kottayam', 'Kottayam'), ('Changanassery', 'Changanassery'), ('Palai', 'Palai'), ('Vaikom', 'Vaikom')]), ('Idukki', [('Idukki', 'Idukki'), ('Thodupuzha', 'Thodupuzha'), ('Munnar', 'Munnar'), ('Adimali', 'Adimali')]), ('Ernakulam', [('Ernakulam', 'Ernakulam'), ('Kochi', 'Kochi'), ('Aluva', 'Aluva'), ('Paravur', 'Paravur')]), ('Thrissur', [('Thrissur', 'Thrissur'), ('Chalakudy', 'Chalakudy'), ('Kodungallur', 'Kodungallur'), ('Irinjalakuda', 'Irinjalakuda')]), ('Palakkad', [('Palakkad', 'Palakkad'), ('Ottapalam', 'Ottapalam'), ('Chittur', 'Chittur'), ('Mannarkkad', 'Mannarkkad')]), ('Malappuram', [('Malappuram', 'Malappuram'), ('Manjeri', 'Manjeri'), ('Tirur', 'Tirur'), ('Perinthalmanna', 'Perinthalmanna')]), ('Kozhikode', [('Calicut', 'Kozhikode (Calicut)'), ('Vadakara', 'Vadakara'), ('Thamarassery', 'Thamarassery'), ('Ramanattukara', 'Ramanattukara')]), ('Wayanad', [('Wayanad', 'Wayanad'), ('Kalpetta', 'Kalpetta'), ('Sulthan Bathery', 'Sulthan Bathery'), ('Mananthavady', 'Mananthavady')]), ('Kannur', [('Thalassery', 'Thalassery'), ('Kannur', 'Kannur'), ('Payyannur', 'Payyannur'), ('Thaliparamba', 'Thaliparamba'), ('Iritty', 'Iritty')]), ('Kasaragod', [('Kasaragod', 'Kasaragod'), ('Kanhangad', 'Kanhangad'), ('Kumbala', 'Kumbala'), ('Cherkala', 'Cherkala')])], max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('height', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('nativity', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matrimony_app.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='matrimony_app.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrimony_app.userprofile')),
            ],
        ),
    ]
