# Generated by Django 3.2.16 on 2023-08-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0003_auto_20230823_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='costom_user_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
