# Generated by Django 3.2.16 on 2023-08-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0004_userprofile_costom_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sibling_relationship',
            field=models.CharField(blank=True, choices=[('brothers', 'Brothers'), ('sisters', 'Sisters'), ('brother_sister', 'Brother and Sister'), ('triplets', 'Triplets'), ('identical_twins', 'Identical Twins'), ('fraternal_twins', 'Fraternal Twins'), ('half_siblings', 'Half-Siblings'), ('step_siblings', 'Step-Siblings'), ('adopted_siblings', 'Adopted Siblings'), ('age_difference_siblings', 'Siblings with Age Difference')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='worked_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
