# Generated by Django 3.2.16 on 2023-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0007_auto_20230825_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('1_day', '1 Day')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
