# Generated by Django 3.2.16 on 2023-08-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0009_subscriptionplan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='costom_user_id',
            new_name='custom_user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
