# Generated by Django 3.2.16 on 2023-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0012_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
