# Generated by Django 3.2.16 on 2023-09-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0014_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sibling_relationship',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='female_siblings',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='male_siblings',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='married_female_siblings',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='married_male_siblings',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='caste',
            field=models.CharField(choices=[('brahmin', 'Brahmin'), ('kshatriya', 'Kshatriya'), ('vaishya', 'Vaishya'), ('shudra', 'Shudra'), ('darzi', 'Darzi'), ('jolaha', 'Jolaha'), ('fakir', 'Fakir'), ('rangrez', 'Rangrez'), ('unspecified', 'unspecified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('unspecified', 'unspecified')], max_length=20),
        ),
    ]
