# Generated by Django 3.2.16 on 2023-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony_app', '0015_auto_20230910_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='female_siblings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='male_siblings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='married_female_siblings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='married_male_siblings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
